### ISSUE TITLE
sample data

### ISSUE THREAD

**Issue by ntustison** [dorianps/LINDA#1]
Hey Dorian,

I'm trying to run this without having my own test subject.  Do you think you could include one of yours in this repository?

Thanks,
Nick

**Comment by dorianps** [comment]
Hi Nick,

The idea is good but the subject is delicate. Our data is protected by IRB and consent forms. There is some lesion data from MICCAI ISLES 2015 challenge, but their license does not seem to allow putting an example here. 

I will look into this. Meanwhile, I can send you an example for trying given your contribution to the algorithm. Or if you have someone with a surgical resection, that should work as well.

**Comment by ntustison** [comment]
That would be great.  If you could send me an image privately, I would really appreciate it.  I have a collaborator who really wants to detect lesions in TBI and I'd like to showcase your stuff as an example.  Thanks.
