### ISSUE TITLE
RF model availability?

### ISSUE THREAD

**Issue by ntustison** [dorianps/LINDA#2]
Hi Dorian,

What about the [RF model](https://github.com/dorianps/LINDA/blob/master/linda_predict.R#L102)?  Can you make it publicly available?

Nick

**Comment by dorianps** [comment]
The model is included in the [Releases](https://github.com/dorianps/LINDA/releases). This is why none should download LINDA from the github Download or Zip buttons, the main repositories do not contain the RF models and other big files, Github simply does not accept files >100mb.

**Comment by ntustison** [comment]
Perfect.  Thanks.
