### ISSUE TITLE
Lesion mask includes non-lesion areas

### ISSUE THREAD

**Issue by yqliu9240** [dorianps/LINDA#31]
Hello!

  I'm coregistering patients' T1 to template. The two patients I analyzed both had subcortical lesion, but the lesion mask contained cortical patches. I wonder if there is a way to correct for that in the code. Their T1 and segmentation files are attached. 

  I'm also doing lesion-to-symptom mapping analyses. Is it valid if I use the Lesion_in_MNI.nii.gz as a starting point, editing it, and then use it for the analysis?

Thank you!
Yuqi
[sub2_T1_LRflip.nii.gz](https://github.com/dorianps/LINDA/files/7592243/sub2_T1_LRflip.nii.gz)
[sub2_Prediction3_native.nii.gz](https://github.com/dorianps/LINDA/files/7592261/sub2_Prediction3_native.nii.gz)
[sub1_T1_LRflip.nii.gz](https://github.com/dorianps/LINDA/files/7592264/sub1_T1_LRflip.nii.gz)
[sub1_Prediction3_native.nii.gz](https://github.com/dorianps/LINDA/files/7592265/sub1_Prediction3_native.nii.gz)

**Comment by dorianps** [comment]
I don't think there is an easy code hack. The two cases seem both to have significant field bias (one side much darker than the other). That is likely contributing to the problem. LINDA tries to correct for field bias, but maybe is not sufficient. I also see a lot of background noise. You can check the intermediate outputs from the pipeline (see the output descriptions in the main page). Your N4 output should becorrected for bias, check if that has still some bias. Check also if brain extraction worked well.

Subject 2 has a pretty good segmentation, except the small cortical error. Cases like this you can resolve manually in just a couple of minutes. Load the segmentation in ITKsnap and then put Active Label: Clear , and Paint Over: Label 1 (see picture attached). Then just go slice by slice, e.g., coronally, and just draw a coarse circle around the lesion you want to delete, which will remove it. There are ways to remove a lesion cluster with code, but is more trouble than it's worth.

![image](https://user-images.githubusercontent.com/9083517/143248759-1869fcfe-8872-4ff0-ba95-8e278d912f2c.png)
