### ISSUE TITLE
 Unsupported file type

### ISSUE THREAD

**Issue by matferr92** [dorianps/LINDA#8]
I'm operating LINDA via Windows Linux Subsistem working with R on command line. The installation process seems to have worked fine, I've got all the required packages and I'm able to start R, sourcing for linda_predict.R and attaching ANTsCore:

```
source('mnt/c/Users/matte/Desktop/LINDA/linda_predict.R')
17:10 Starting LINDA v0.2.7 ...

Loading

 required package: ANTsRCore

Attaching package: ‘ANTsRCore

The following object is masked from ‘package:stats’:

    var

The following objects are masked from ‘package:base’:

    all, any, apply, max, min, prod, range, sum

randomForest 4.6-12
Type rfNews() to see new features/changes/bug fixes.

```
Everything seems to be working until I have to select a file to be processed by LINDA. I get an unsupported file type error:
```
Enter file name: "mnt/c/Users/matte/Desktop/tests/shared/wsMT05374-0002-00001-000176-01.nii"
Error in eval(ei, envir) :
  Unsupported file type -> wsMT05374-0002-00001-000176-01.nii"
```
 I'm providing regular T1 weighted scans in .nii format as suggested by the instructions. I've been trying with several images but I couldn't get it to work so far. 
Am I doing something wrong here? 

Any suggestion would be helpful. Thanks.

**Comment by dorianps** [comment]
Is this resolved now? In case this happens again, you can try opening the image in ITKsnap, then save it with .nii.gz. It's a temporary solution just to make sure Linda is working, but needs a more stable solution if the problem represents.

**Comment by matferr92** [comment]
Thank you Dorian, 
I fixed it, yes. I was just making a mistake in giving it the location of the file. I had to remove those double quotation marks enclosing the path. 

Thank you for your help.

Matteo Ferrante
