### ISSUE TITLE
Error in running prediction

### ISSUE THREAD

**Issue by 7alberto** [dorianps/LINDA#9]
Software versions:
- R (3.4.4)
- ANTsR (0.6.1) [also tried 0.3.2 and 0.4.0]
- randomForest (4.6-12) [also tried 4.6-14]
- LINDA (v.0.2.6)

When sourcing the "linda_predict" script, everything works fine up to the 1st prediction step:

```
16:47 Starting LINDA v0.2.6 ...
Loading required package: ANTsRCore
randomForest 4.6-12
Enter file name: T1.nii.gz
16:48 Loading file: T1.nii.gz 
16:48 Creating folder: ./linda 
16:48 Loading template... 
16:48 Skull stripping... (long process) 
17:06 Saving skull stripped files 
17:06 Loading LINDA model 
17:06 Computing asymmetry mask... 
17:08 Saving asymmetry mask... 
17:08 Running 1st registration... 
17:11 Feature calculation... 
17:15 Running 1st prediction... 
Error in which(submask > 0) : argument to 'which' is not logical
```

It seems that, inside the "mrvnrfs.predict_chunks" function, the data type for the submask cannot be used by the "which" function. I did some debugging, and it turns out that "submask" is actually of type "antsImage", with max = 1 and min = 0:

```
antsImage
  Pixel Type          : unsigned char 
  Components Per Pixel: 1 
  Dimensions          : 256x256x192 
  Voxel Spacing       : 1x1x0.999995172023773 
  Origin              : 103.2539 -120.9078 -117.9969 
  Direction           : -0.008816802 0.9962615 0.08593764 -0.01123489 -0.08603425 0.9962288 -0.999898 -0.007818053 -0.01195143
```

I cannot figure out what's wrong here. Any hint? I attach here the T1 example I am currently using.

Thanks a lot,
Alberto
[T1.nii.gz](https://github.com/dorianps/LINDA/files/2163838/T1.nii.gz)

**Comment by dorianps** [comment]
Will give it a try to see what's wrong. How old is your LINDA/ANTsR
installation?

**Comment by dorianps** [comment]
Apologies, just noticed you already put the versions.

**Comment by dorianps** [comment]
Alberto, version 0.2.6 might be the problem. I think I fixed this problem
in 0.2.7. Get it here
https://github.com/dorianps/LINDA/releases/download/0.2.7/LINDA_v0.2.7.zip

**Comment by 7alberto** [comment]
The new version of LINDA made it! It seems to be working properly.
Thanks so much for your support, Dorian.

Best,
Alberto
